# Generated by Django 5.0.6 on 2026-04-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleinvoiceline',
            old_name='document',
            new_name='invoice',
        ),
    ]
