# Generated by Django 5.0.6 on 2025-10-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_subgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extent',
            options={'ordering': ['name'], 'verbose_name': 'Medida', 'verbose_name_plural': 'Medidas'},
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='ProductGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productgroup', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Subgrupo'),
        ),
    ]
