# Generated by Django 5.0.6 on 2025-10-28 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_branch_address_alter_branch_company_and_more'),
        ('inventory', '0006_hangers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hangers',
            new_name='Hanger',
        ),
    ]
