# Generated by Django 5.0.6 on 2025-10-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_hangers_hanger'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Hanger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.hanger', verbose_name='Percha'),
        ),
    ]
