# Generated by Django 5.0.6 on 2025-10-29 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryfow_stockmovement_stockmovementline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryfow',
            name='signo',
            field=models.CharField(max_length=150, verbose_name='Signo'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryfow'),
        ),
    ]
