# Generated by Django 5.0 on 2025-10-21 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_person',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contact_profile', to='people.person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_security_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
