# Generated by Django 5.0.6 on 2025-10-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_employee_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identification_type',
            field=models.CharField(choices=[('CED', 'Cédula'), ('RUC', 'RUC'), ('PAS', 'Pasaporte')], default='CED', max_length=3, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de identificación'),
        ),
    ]
