# Generated by Django 5.0.6 on 2025-10-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_identification_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'CLiente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='symbol',
            field=models.CharField(max_length=25, verbose_name='Simbolo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Compañia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Genero', to='people.gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.parish', verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídica')], default='N', max_length=1, verbose_name='Tipo de Persona'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
