# Generated by Django 5.0.6 on 2025-10-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_client_options_alter_gender_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name': 'Parroquia', 'verbose_name_plural': 'Parroquias'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
