# Generated by Django 5.0.6 on 2025-10-28 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_country_options_alter_gender_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.gender', verbose_name='Genero'),
        ),
    ]
