# Generated by Django 5.0.6 on 2025-10-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company_name',
        ),
    ]
