# Generated by Django 5.0.6 on 2025-12-02 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_branch_created_by_branch_updated_by_company_branch_and_more'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('people', '0003_client_created_by_client_updated_by_employee_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('document_date', models.DateField(auto_now_add=True, verbose_name='Fecha del documento')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia externa')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmado'), ('cancelled', 'Anulado')], default='draft', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal')),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuentos')),
                ('zero_tax_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Base sin Impuestos')),
                ('tax_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Base_Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('invoice_number', models.CharField(max_length=30, verbose_name='Número de factura')),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.branch')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movementflow', verbose_name='Flujo de inventario')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='PurchaseMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cantidad')),
                ('fraction_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Fraccion')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Unitario')),
                ('fraction_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Fraccion')),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuentos')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Impuestos')),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.branch')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='purchases.purchaseheader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.branch')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'purchases_supplier',
            },
        ),
    ]
