# Generated by Django 5.0.6 on 2026-03-07 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='caducidad',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha del caducidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='count',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cuenta contable'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='establecimiento',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='establecimiento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='punto',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Punto de emisiòn'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='web',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Pagina web'),
        ),
    ]
