# Generated by Django 4.2.11 on 2026-03-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_supplier_caducidad_supplier_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pagina web'),
        ),
    ]
