# Generated by Django 5.0 on 2025-10-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='person',
        ),
    ]
