# Generated by Django 5.0 on 2025-10-21 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_person'),
        ('people', '0003_employee_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='people.person'),
        ),
    ]
