# Generated by Django 5.0.6 on 2025-10-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
