# Generated by Django 5.0.6 on 2025-10-31 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_branch_created_at_branch_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='company',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.branch'),
        ),
    ]
