# Generated by Django 5.2.7 on 2025-10-25 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_person'),
        ('users', '0004_user_branch_alter_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Personal'), ('VIEWER', 'Consulta')], default='VIEWER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía usuario-empresa',
                'verbose_name_plural': 'Membresías usuario-empresa',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
