# Generated by Django 5.0.6 on 2025-10-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_person'),
        ('users', '0005_usercompanymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='companies.company'),
        ),
    ]
