# Generated by Django 4.2.11 on 2026-03-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('last_number', models.IntegerField(default=0)),
                ('padding', models.IntegerField(default=9)),
            ],
        ),
    ]
