# Generated by Django 5.0.6 on 2026-04-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('last_number', models.IntegerField(default=0)),
                ('padding', models.IntegerField(default=9)),
                ('establishment', models.CharField(max_length=3)),
                ('emission_point', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado de Documento',
                'verbose_name_plural': 'Estados de Documento',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='DocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_inventory', models.BooleanField(default=False)),
                ('generate_accounting', models.BooleanField(default=False)),
                ('electronic', models.BooleanField(default=False)),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentsequence')),
                ('initial_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_documents', to='documents.documentstatus')),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Configuración de Documento',
                'verbose_name_plural': 'Configuraciones de Documento',
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_from', to='documents.documentstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_to', to='documents.documentstatus')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'unique_together': {('document_type', 'from_status', 'to_status')},
            },
        ),
    ]
