# Generated by Django 5.0.6 on 2026-04-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentworkflow',
            old_name='action_name',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='use_sequence',
        ),
        migrations.AlterField(
            model_name='documentsettings',
            name='initial_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_documents', to='documents.documentstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='documentworkflow',
            unique_together={('document_type', 'from_status', 'to_status')},
        ),
    ]
