# Generated by Django 5.0.6 on 2026-04-01 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_action_name_documentworkflow_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsettings',
            name='initial_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentstatus'),
        ),
    ]
