# Generated by Django 5.0.6 on 2026-04-01 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentsettings_initial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsettings',
            name='initial_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='initial_documents', to='documents.documentstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentsettings',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentsequence'),
        ),
    ]
