# Generated by Django 5.0.6 on 2026-03-13 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_inventory', models.BooleanField(default=False)),
                ('generate_accounting', models.BooleanField(default=False)),
                ('electronic', models.BooleanField(default=False)),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('initial_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_documents', to='documents.documentstatus')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentsequence')),
            ],
            options={
                'verbose_name': 'Configuración de Documento',
                'verbose_name_plural': 'Configuraciones de Documento',
            },
        ),
    ]
