# Generated by Django 5.0.6 on 2026-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentsettings_initial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsequence',
            name='emission_point',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='establishment',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
