# Generated by Django 5.0.6 on 2026-03-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=50)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_from', to='documents.documentstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_to', to='documents.documentstatus')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
    ]
