# Generated by Django 5.0.6 on 2025-11-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementFlow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('title', models.CharField(max_length=150, verbose_name='Tilulo')),
                ('signo', models.CharField(choices=[('+', '(+) el inventario'), ('-', '(-) el inventario')], default='+', max_length=1, verbose_name='Suma o Resta')),
                ('category', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('TR', 'Transferencia'), ('ADJ', 'Ajuste')], default='IN', max_length=4)),
                ('affects_inventory', models.BooleanField(default=True, verbose_name='Afecta Inventario')),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.branch')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='companies.company')),
            ],
            options={
                'verbose_name': 'Flujo de inventario',
                'verbose_name_plural': 'Flujos de inventario',
                'ordering': ['name'],
            },
        ),
    ]
